kind: PersistentVolume
apiVersion: v1
metadata:
  name: server-keytab
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/keytab"