apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    keerberosService: nn
  name: nn
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    keerberosService: nn
status:
  loadBalancer: {}
